"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.api.projects_api import ProjectsApi  # noqa: E501


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_institute(self):
        """Test case for delete_institute

        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        """
        pass

    def test_delete_project_application_specific(self):
        """Test case for delete_project_application_specific

        """
        pass

    def test_delete_project_files(self):
        """Test case for delete_project_files

        """
        pass

    def test_get_institute(self):
        """Test case for get_institute

        """
        pass

    def test_get_institutes(self):
        """Test case for get_institutes

        """
        pass

    def test_get_project(self):
        """Test case for get_project

        """
        pass

    def test_get_project_applications(self):
        """Test case for get_project_applications

        """
        pass

    def test_get_project_download_file(self):
        """Test case for get_project_download_file

        """
        pass

    def test_get_project_epd_sites(self):
        """Test case for get_project_epd_sites

        """
        pass

    def test_get_project_file_content(self):
        """Test case for get_project_file_content

        """
        pass

    def test_get_project_files(self):
        """Test case for get_project_files

        """
        pass

    def test_get_project_types(self):
        """Test case for get_project_types

        """
        pass

    def test_get_projects(self):
        """Test case for get_projects

        """
        pass

    def test_post_institutes(self):
        """Test case for post_institutes

        """
        pass

    def test_post_project_applications(self):
        """Test case for post_project_applications

        """
        pass

    def test_post_project_files(self):
        """Test case for post_project_files

        This create project files endpoint actually only stores the file size of a project_id + key combination  # noqa: E501
        """
        pass

    def test_post_projects(self):
        """Test case for post_projects

        """
        pass


if __name__ == '__main__':
    unittest.main()
