"""
    Apis

    Api containing all apis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.auth
from igtcloud.client.services.auth.model.login_model import LoginModel


class TestLoginModel(unittest.TestCase):
    """LoginModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginModel(self):
        """Test LoginModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoginModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
