"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.api.hospitals_api import HospitalsApi  # noqa: E501


class TestHospitalsApi(unittest.TestCase):
    """HospitalsApi unit test stubs"""

    def setUp(self):
        self.api = HospitalsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_study_files_resource(self):
        """Test case for delete_study_files_resource

        """
        pass

    def test_delete_study_resource(self):
        """Test case for delete_study_resource

        """
        pass

    def test_delete_study_series_resource(self):
        """Test case for delete_study_series_resource

        """
        pass

    def test_get_all_hospitals_resource(self):
        """Test case for get_all_hospitals_resource

        """
        pass

    def test_get_series_list_resource(self):
        """Test case for get_series_list_resource

        """
        pass

    def test_get_series_preview_resource(self):
        """Test case for get_series_preview_resource

        """
        pass

    def test_get_series_resource(self):
        """Test case for get_series_resource

        """
        pass

    def test_get_studies_resource(self):
        """Test case for get_studies_resource

        """
        pass

    def test_get_study_download_file_resource(self):
        """Test case for get_study_download_file_resource

        """
        pass

    def test_get_study_files_resource(self):
        """Test case for get_study_files_resource

        """
        pass

    def test_get_study_resource(self):
        """Test case for get_study_resource

        """
        pass

    def test_get_study_series_list_resource(self):
        """Test case for get_study_series_list_resource

        """
        pass

    def test_patch_study_resource(self):
        """Test case for patch_study_resource

        """
        pass

    def test_post_studies_resource(self):
        """Test case for post_studies_resource

        """
        pass

    def test_post_study_annotation_state_resource(self):
        """Test case for post_study_annotation_state_resource

        """
        pass

    def test_post_study_download_link_resource(self):
        """Test case for post_study_download_link_resource

        """
        pass

    def test_post_study_electronic_record_state_resource(self):
        """Test case for post_study_electronic_record_state_resource

        """
        pass

    def test_post_study_files_resource(self):
        """Test case for post_study_files_resource

        This create study files endpoint actually only stores the file size of a study_id + key combination  # noqa: E501
        """
        pass

    def test_put_study_resource(self):
        """Test case for put_study_resource

        """
        pass

    def test_put_study_series_resource(self):
        """Test case for put_study_series_resource

        """
        pass


if __name__ == '__main__':
    unittest.main()
