"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.annotation_series_model_all_of import AnnotationSeriesModelAllOf
from igtcloud.client.services.entities.model.annotation_study_model import AnnotationStudyModel
from igtcloud.client.services.entities.model.series_model import SeriesModel
globals()['AnnotationSeriesModelAllOf'] = AnnotationSeriesModelAllOf
globals()['AnnotationStudyModel'] = AnnotationStudyModel
globals()['SeriesModel'] = SeriesModel
from igtcloud.client.services.entities.model.annotation_series_model import AnnotationSeriesModel


class TestAnnotationSeriesModel(unittest.TestCase):
    """AnnotationSeriesModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationSeriesModel(self):
        """Test AnnotationSeriesModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationSeriesModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
