"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.annotation_study_model_all_of import AnnotationStudyModelAllOf


class TestAnnotationStudyModelAllOf(unittest.TestCase):
    """AnnotationStudyModelAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationStudyModelAllOf(self):
        """Test AnnotationStudyModelAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationStudyModelAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
