"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.base_study import BaseStudy
from igtcloud.client.services.entities.model.patient_model import PatientModel
globals()['BaseStudy'] = BaseStudy
globals()['PatientModel'] = PatientModel
from igtcloud.client.services.entities.model.study import Study


class TestStudy(unittest.TestCase):
    """Study unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudy(self):
        """Test Study"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Study()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
