"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.config_model import ConfigModel
from igtcloud.client.services.entities.model.credentials_model import CredentialsModel
globals()['ConfigModel'] = ConfigModel
globals()['CredentialsModel'] = CredentialsModel
from igtcloud.client.services.entities.model.storage_model import StorageModel


class TestStorageModel(unittest.TestCase):
    """StorageModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageModel(self):
        """Test StorageModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
