"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.account_status_model import AccountStatusModel


class TestAccountStatusModel(unittest.TestCase):
    """AccountStatusModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountStatusModel(self):
        """Test AccountStatusModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountStatusModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
