"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.group_model import GroupModel


class TestGroupModel(unittest.TestCase):
    """GroupModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupModel(self):
        """Test GroupModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
