"""
    Apis

    Api containing all apis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.auth
from igtcloud.client.services.auth.model.organization import Organization
globals()['Organization'] = Organization
from igtcloud.client.services.auth.model.organizations import Organizations


class TestOrganizations(unittest.TestCase):
    """Organizations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizations(self):
        """Test Organizations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Organizations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
