"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.marvel_study_all_of import MarvelStudyAllOf


class TestMarvelStudyAllOf(unittest.TestCase):
    """MarvelStudyAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMarvelStudyAllOf(self):
        """Test MarvelStudyAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MarvelStudyAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
