"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.contact import Contact
from igtcloud.client.services.entities.model.organization_role import OrganizationRole
globals()['Contact'] = Contact
globals()['OrganizationRole'] = OrganizationRole
from igtcloud.client.services.entities.model.profile import Profile


class TestProfile(unittest.TestCase):
    """Profile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProfile(self):
        """Test Profile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Profile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
