"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.applications_model import ApplicationsModel


class TestApplicationsModel(unittest.TestCase):
    """ApplicationsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationsModel(self):
        """Test ApplicationsModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationsModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
