"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.base_study_model import BaseStudyModel
from igtcloud.client.services.entities.model.patient_model import PatientModel
globals()['BaseStudyModel'] = BaseStudyModel
globals()['PatientModel'] = PatientModel
from igtcloud.client.services.entities.model.study_model import StudyModel


class TestStudyModel(unittest.TestCase):
    """StudyModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudyModel(self):
        """Test StudyModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudyModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
