"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.core_labs_study_model_all_of import CoreLabsStudyModelAllOf


class TestCoreLabsStudyModelAllOf(unittest.TestCase):
    """CoreLabsStudyModelAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoreLabsStudyModelAllOf(self):
        """Test CoreLabsStudyModelAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CoreLabsStudyModelAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
