"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.hospital_model import HospitalModel
globals()['HospitalModel'] = HospitalModel
from igtcloud.client.services.entities.model.hospital_response import HospitalResponse


class TestHospitalResponse(unittest.TestCase):
    """HospitalResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHospitalResponse(self):
        """Test HospitalResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HospitalResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
