"""
    Apis

    Api containing all apis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.auth
from igtcloud.client.services.auth.model.allowed import Allowed
from igtcloud.client.services.auth.model.credentials import Credentials
globals()['Allowed'] = Allowed
globals()['Credentials'] = Credentials
from igtcloud.client.services.auth.model.s3_credential import S3Credential


class TestS3Credential(unittest.TestCase):
    """S3Credential unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS3Credential(self):
        """Test S3Credential"""
        # FIXME: construct object with mandatory attributes with example values
        # model = S3Credential()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
