"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.base_study_model import BaseStudyModel
from igtcloud.client.services.entities.model.marvel_study_model_all_of import MarvelStudyModelAllOf
from igtcloud.client.services.entities.model.patient_model import PatientModel
globals()['BaseStudyModel'] = BaseStudyModel
globals()['MarvelStudyModelAllOf'] = MarvelStudyModelAllOf
globals()['PatientModel'] = PatientModel
from igtcloud.client.services.entities.model.marvel_study_model import MarvelStudyModel


class TestMarvelStudyModel(unittest.TestCase):
    """MarvelStudyModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMarvelStudyModel(self):
        """Test MarvelStudyModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MarvelStudyModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
