"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.annotation_study_all_of import AnnotationStudyAllOf
from igtcloud.client.services.entities.model.core_labs_study import CoreLabsStudy
from igtcloud.client.services.entities.model.patient import Patient
globals()['AnnotationStudyAllOf'] = AnnotationStudyAllOf
globals()['CoreLabsStudy'] = CoreLabsStudy
globals()['Patient'] = Patient
from igtcloud.client.services.entities.model.annotation_study import AnnotationStudy


class TestAnnotationStudy(unittest.TestCase):
    """AnnotationStudy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationStudy(self):
        """Test AnnotationStudy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationStudy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
