"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.i_guide_u_study_all_of import IGuideUStudyAllOf
from igtcloud.client.services.entities.model.root_study import RootStudy
globals()['IGuideUStudyAllOf'] = IGuideUStudyAllOf
globals()['RootStudy'] = RootStudy
from igtcloud.client.services.entities.model.i_guide_u_study import IGuideUStudy


class TestIGuideUStudy(unittest.TestCase):
    """IGuideUStudy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIGuideUStudy(self):
        """Test IGuideUStudy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IGuideUStudy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
