"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.study_model import StudyModel
globals()['StudyModel'] = StudyModel
from igtcloud.client.services.entities.model.study_response import StudyResponse


class TestStudyResponse(unittest.TestCase):
    """StudyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudyResponse(self):
        """Test StudyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
