"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.patient_model import PatientModel


class TestPatientModel(unittest.TestCase):
    """PatientModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatientModel(self):
        """Test PatientModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatientModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
