"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.api.tasks_api import TasksApi  # noqa: E501


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_task_resource(self):
        """Test case for get_task_resource

        """
        pass

    def test_post_task_resource(self):
        """Test case for post_task_resource

        """
        pass


if __name__ == '__main__':
    unittest.main()
