"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.marvel_series_model import MarvelSeriesModel
globals()['MarvelSeriesModel'] = MarvelSeriesModel
from igtcloud.client.services.entities.model.marvel_series_list_response import MarvelSeriesListResponse


class TestMarvelSeriesListResponse(unittest.TestCase):
    """MarvelSeriesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMarvelSeriesListResponse(self):
        """Test MarvelSeriesListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MarvelSeriesListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
