"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.echo_nav_all_of import EchoNavAllOf


class TestEchoNavAllOf(unittest.TestCase):
    """EchoNavAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEchoNavAllOf(self):
        """Test EchoNavAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EchoNavAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
