"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.user_settings import UserSettings


class TestUserSettings(unittest.TestCase):
    """UserSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserSettings(self):
        """Test UserSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
