"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.project_model import ProjectModel


class TestProjectModel(unittest.TestCase):
    """ProjectModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectModel(self):
        """Test ProjectModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
