"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.hospital_model import HospitalModel
globals()['HospitalModel'] = HospitalModel
from igtcloud.client.services.entities.model.hospitals_response import HospitalsResponse


class TestHospitalsResponse(unittest.TestCase):
    """HospitalsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHospitalsResponse(self):
        """Test HospitalsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HospitalsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
