"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.annotation_study import AnnotationStudy
from igtcloud.client.services.entities.model.base_study import BaseStudy
from igtcloud.client.services.entities.model.core_labs_study import CoreLabsStudy
from igtcloud.client.services.entities.model.echo_nav import EchoNav
from igtcloud.client.services.entities.model.epd_study import EpdStudy
from igtcloud.client.services.entities.model.i_guide_u_study import IGuideUStudy
from igtcloud.client.services.entities.model.marvel_study import MarvelStudy
from igtcloud.client.services.entities.model.study import Study
from igtcloud.client.services.entities.model.we_trust_study import WeTrustStudy
globals()['AnnotationStudy'] = AnnotationStudy
globals()['BaseStudy'] = BaseStudy
globals()['CoreLabsStudy'] = CoreLabsStudy
globals()['EchoNav'] = EchoNav
globals()['EpdStudy'] = EpdStudy
globals()['IGuideUStudy'] = IGuideUStudy
globals()['MarvelStudy'] = MarvelStudy
globals()['Study'] = Study
globals()['WeTrustStudy'] = WeTrustStudy
from igtcloud.client.services.entities.model.root_study import RootStudy


class TestRootStudy(unittest.TestCase):
    """RootStudy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRootStudy(self):
        """Test RootStudy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RootStudy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
