"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_user(self):
        """Test case for delete_user

        """
        pass

    def test_delete_user_storage_files(self):
        """Test case for delete_user_storage_files

        """
        pass

    def test_delete_user_storage_training_settings(self):
        """Test case for delete_user_storage_training_settings

        """
        pass

    def test_get_me(self):
        """Test case for get_me

        """
        pass

    def test_get_user(self):
        """Test case for get_user

        """
        pass

    def test_get_user_storage(self):
        """Test case for get_user_storage

        """
        pass

    def test_get_user_storage_download_files(self):
        """Test case for get_user_storage_download_files

        """
        pass

    def test_get_user_storage_files(self):
        """Test case for get_user_storage_files

        """
        pass

    def test_get_users(self):
        """Test case for get_users

        """
        pass

    def test_post_resend_activation(self):
        """Test case for post_resend_activation

        """
        pass

    def test_post_reset_mfa(self):
        """Test case for post_reset_mfa

        """
        pass

    def test_post_user_profile(self):
        """Test case for post_user_profile

        """
        pass

    def test_post_users(self):
        """Test case for post_users

        """
        pass

    def test_put_user(self):
        """Test case for put_user

        """
        pass


if __name__ == '__main__':
    unittest.main()
