"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.api.organizations_api import OrganizationsApi  # noqa: E501


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_service_resource(self):
        """Test case for delete_service_resource

        """
        pass

    def test_get_groups_resource(self):
        """Test case for get_groups_resource

        """
        pass

    def test_get_services_resource(self):
        """Test case for get_services_resource

        """
        pass

    def test_get_users_groups_resource(self):
        """Test case for get_users_groups_resource

        """
        pass

    def test_post_services_resource(self):
        """Test case for post_services_resource

        """
        pass

    def test_put_users_groups_resource(self):
        """Test case for put_users_groups_resource

        """
        pass


if __name__ == '__main__':
    unittest.main()
