"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.project_types_response import ProjectTypesResponse


class TestProjectTypesResponse(unittest.TestCase):
    """ProjectTypesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectTypesResponse(self):
        """Test ProjectTypesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectTypesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
