"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.root_study_model import RootStudyModel
globals()['RootStudyModel'] = RootStudyModel
from igtcloud.client.services.entities.model.root_studies_model import RootStudiesModel


class TestRootStudiesModel(unittest.TestCase):
    """RootStudiesModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRootStudiesModel(self):
        """Test RootStudiesModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RootStudiesModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
