"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.epd_study_model import EpdStudyModel
globals()['EpdStudyModel'] = EpdStudyModel
from igtcloud.client.services.entities.model.epd_studies_response import EpdStudiesResponse


class TestEpdStudiesResponse(unittest.TestCase):
    """EpdStudiesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEpdStudiesResponse(self):
        """Test EpdStudiesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EpdStudiesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
