"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.we_trust_study_model_all_of import WeTrustStudyModelAllOf


class TestWeTrustStudyModelAllOf(unittest.TestCase):
    """WeTrustStudyModelAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWeTrustStudyModelAllOf(self):
        """Test WeTrustStudyModelAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WeTrustStudyModelAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
