"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.account_status_model import AccountStatusModel
from igtcloud.client.services.entities.model.profile_model import ProfileModel
from igtcloud.client.services.entities.model.user_settings_model import UserSettingsModel
globals()['AccountStatusModel'] = AccountStatusModel
globals()['ProfileModel'] = ProfileModel
globals()['UserSettingsModel'] = UserSettingsModel
from igtcloud.client.services.entities.model.user_info_model import UserInfoModel


class TestUserInfoModel(unittest.TestCase):
    """UserInfoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserInfoModel(self):
        """Test UserInfoModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserInfoModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
