"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.storage_config import StorageConfig
from igtcloud.client.services.entities.model.storage_credentials import StorageCredentials
globals()['StorageConfig'] = StorageConfig
globals()['StorageCredentials'] = StorageCredentials
from igtcloud.client.services.entities.model.storage import Storage


class TestStorage(unittest.TestCase):
    """Storage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorage(self):
        """Test Storage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Storage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
