"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.ai_suite_project_all_of import AISuiteProjectAllOf
from igtcloud.client.services.entities.model.ai_suite_resource import AISuiteResource
globals()['AISuiteProjectAllOf'] = AISuiteProjectAllOf
globals()['AISuiteResource'] = AISuiteResource
from igtcloud.client.services.entities.model.ai_suite_project import AISuiteProject


class TestAISuiteProject(unittest.TestCase):
    """AISuiteProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAISuiteProject(self):
        """Test AISuiteProject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AISuiteProject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
