"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.i_guide_u_study_model import IGuideUStudyModel
globals()['IGuideUStudyModel'] = IGuideUStudyModel
from igtcloud.client.services.entities.model.i_guide_u_study_response import IGuideUStudyResponse


class TestIGuideUStudyResponse(unittest.TestCase):
    """IGuideUStudyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIGuideUStudyResponse(self):
        """Test IGuideUStudyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IGuideUStudyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
