"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.annotation_study import AnnotationStudy
from igtcloud.client.services.entities.model.base_study_all_of import BaseStudyAllOf
from igtcloud.client.services.entities.model.clinical_image_library_study import ClinicalImageLibraryStudy
from igtcloud.client.services.entities.model.core_labs_study import CoreLabsStudy
from igtcloud.client.services.entities.model.echo_nav_study import EchoNavStudy
from igtcloud.client.services.entities.model.marvel_study import MarvelStudy
from igtcloud.client.services.entities.model.patient import Patient
from igtcloud.client.services.entities.model.root_study import RootStudy
from igtcloud.client.services.entities.model.study import Study
from igtcloud.client.services.entities.model.we_trust_study import WeTrustStudy
globals()['AnnotationStudy'] = AnnotationStudy
globals()['BaseStudyAllOf'] = BaseStudyAllOf
globals()['ClinicalImageLibraryStudy'] = ClinicalImageLibraryStudy
globals()['CoreLabsStudy'] = CoreLabsStudy
globals()['EchoNavStudy'] = EchoNavStudy
globals()['MarvelStudy'] = MarvelStudy
globals()['Patient'] = Patient
globals()['RootStudy'] = RootStudy
globals()['Study'] = Study
globals()['WeTrustStudy'] = WeTrustStudy
from igtcloud.client.services.entities.model.base_study import BaseStudy


class TestBaseStudy(unittest.TestCase):
    """BaseStudy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseStudy(self):
        """Test BaseStudy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BaseStudy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
