"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.ai_suite_provider_all_of import AISuiteProviderAllOf
from igtcloud.client.services.entities.model.ai_suite_resource import AISuiteResource
globals()['AISuiteProviderAllOf'] = AISuiteProviderAllOf
globals()['AISuiteResource'] = AISuiteResource
from igtcloud.client.services.entities.model.ai_suite_provider import AISuiteProvider


class TestAISuiteProvider(unittest.TestCase):
    """AISuiteProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAISuiteProvider(self):
        """Test AISuiteProvider"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AISuiteProvider()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
