"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.api.projects_api import ProjectsApi  # noqa: E501


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_project_files_resource(self):
        """Test case for delete_project_files_resource

        """
        pass

    def test_get_hospital_resource(self):
        """Test case for get_hospital_resource

        """
        pass

    def test_get_hospitals_resource(self):
        """Test case for get_hospitals_resource

        """
        pass

    def test_get_project_download_file_resource(self):
        """Test case for get_project_download_file_resource

        """
        pass

    def test_get_project_files_resource(self):
        """Test case for get_project_files_resource

        """
        pass

    def test_get_project_resource(self):
        """Test case for get_project_resource

        """
        pass

    def test_get_project_types_resource(self):
        """Test case for get_project_types_resource

        """
        pass

    def test_get_projects_resource(self):
        """Test case for get_projects_resource

        """
        pass

    def test_post_hospitals_resource(self):
        """Test case for post_hospitals_resource

        """
        pass

    def test_post_project_files_resource(self):
        """Test case for post_project_files_resource

        This create project files endpoint actually only stores the file size of a project_id + key combination  # noqa: E501
        """
        pass

    def test_post_projects_resource(self):
        """Test case for post_projects_resource

        """
        pass


if __name__ == '__main__':
    unittest.main()
