"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.annotation_study import AnnotationStudy
globals()['AnnotationStudy'] = AnnotationStudy
from igtcloud.client.services.entities.model.annotation_series_all_of import AnnotationSeriesAllOf


class TestAnnotationSeriesAllOf(unittest.TestCase):
    """AnnotationSeriesAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationSeriesAllOf(self):
        """Test AnnotationSeriesAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationSeriesAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
