"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.marvel_study_model import MarvelStudyModel
globals()['MarvelStudyModel'] = MarvelStudyModel
from igtcloud.client.services.entities.model.marvel_series_model_all_of import MarvelSeriesModelAllOf


class TestMarvelSeriesModelAllOf(unittest.TestCase):
    """MarvelSeriesModelAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMarvelSeriesModelAllOf(self):
        """Test MarvelSeriesModelAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MarvelSeriesModelAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
