"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.annotation_study_model_all_of import AnnotationStudyModelAllOf
from igtcloud.client.services.entities.model.core_labs_study_model import CoreLabsStudyModel
from igtcloud.client.services.entities.model.patient_model import PatientModel
globals()['AnnotationStudyModelAllOf'] = AnnotationStudyModelAllOf
globals()['CoreLabsStudyModel'] = CoreLabsStudyModel
globals()['PatientModel'] = PatientModel
from igtcloud.client.services.entities.model.annotation_study_model import AnnotationStudyModel


class TestAnnotationStudyModel(unittest.TestCase):
    """AnnotationStudyModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationStudyModel(self):
        """Test AnnotationStudyModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationStudyModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
