"""
    IGT Cloud Action

    IGT Cloud action  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.action
from igtcloud.client.services.action.model.update_database_request import UpdateDatabaseRequest


class TestUpdateDatabaseRequest(unittest.TestCase):
    """UpdateDatabaseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateDatabaseRequest(self):
        """Test UpdateDatabaseRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateDatabaseRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
