"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.we_trust_series_model import WeTrustSeriesModel
globals()['WeTrustSeriesModel'] = WeTrustSeriesModel
from igtcloud.client.services.entities.model.we_trust_series_list_response import WeTrustSeriesListResponse


class TestWeTrustSeriesListResponse(unittest.TestCase):
    """WeTrustSeriesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWeTrustSeriesListResponse(self):
        """Test WeTrustSeriesListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WeTrustSeriesListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
