"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.core_labs_study_model import CoreLabsStudyModel
globals()['CoreLabsStudyModel'] = CoreLabsStudyModel
from igtcloud.client.services.entities.model.core_labs_studies_response import CoreLabsStudiesResponse


class TestCoreLabsStudiesResponse(unittest.TestCase):
    """CoreLabsStudiesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoreLabsStudiesResponse(self):
        """Test CoreLabsStudiesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CoreLabsStudiesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
