"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.echo_nav_series_model import EchoNavSeriesModel
globals()['EchoNavSeriesModel'] = EchoNavSeriesModel
from igtcloud.client.services.entities.model.echo_nav_series_response import EchoNavSeriesResponse


class TestEchoNavSeriesResponse(unittest.TestCase):
    """EchoNavSeriesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEchoNavSeriesResponse(self):
        """Test EchoNavSeriesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EchoNavSeriesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
