"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.study import Study
globals()['Study'] = Study
from igtcloud.client.services.entities.model.igt_cloud_series_all_of import IgtCloudSeriesAllOf


class TestIgtCloudSeriesAllOf(unittest.TestCase):
    """IgtCloudSeriesAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIgtCloudSeriesAllOf(self):
        """Test IgtCloudSeriesAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IgtCloudSeriesAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
