"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.annotation_study_model import AnnotationStudyModel
from igtcloud.client.services.entities.model.base_study_model_all_of import BaseStudyModelAllOf
from igtcloud.client.services.entities.model.core_labs_study_model import CoreLabsStudyModel
from igtcloud.client.services.entities.model.patient_model import PatientModel
from igtcloud.client.services.entities.model.root_study_model import RootStudyModel
globals()['AnnotationStudyModel'] = AnnotationStudyModel
globals()['BaseStudyModelAllOf'] = BaseStudyModelAllOf
globals()['CoreLabsStudyModel'] = CoreLabsStudyModel
globals()['PatientModel'] = PatientModel
globals()['RootStudyModel'] = RootStudyModel
from igtcloud.client.services.entities.model.base_study_model import BaseStudyModel


class TestBaseStudyModel(unittest.TestCase):
    """BaseStudyModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseStudyModel(self):
        """Test BaseStudyModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BaseStudyModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
