"""
    Apis

    Api containing all apis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.auth
from igtcloud.client.services.auth.model.logout_response import LogoutResponse


class TestLogoutResponse(unittest.TestCase):
    """LogoutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogoutResponse(self):
        """Test LogoutResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LogoutResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
