"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.api.epd_sites_api import EpdSitesApi  # noqa: E501


class TestEpdSitesApi(unittest.TestCase):
    """EpdSitesApi unit test stubs"""

    def setUp(self):
        self.api = EpdSitesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_epd_site_specific(self):
        """Test case for delete_epd_site_specific

        """
        pass

    def test_get_epd_site_specific(self):
        """Test case for get_epd_site_specific

        """
        pass

    def test_get_epd_sites(self):
        """Test case for get_epd_sites

        """
        pass

    def test_post_epd_sites(self):
        """Test case for post_epd_sites

        """
        pass

    def test_put_epd_site_specific(self):
        """Test case for put_epd_site_specific

        """
        pass


if __name__ == '__main__':
    unittest.main()
