"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.annotation_study_model import AnnotationStudyModel
globals()['AnnotationStudyModel'] = AnnotationStudyModel
from igtcloud.client.services.entities.model.annotation_studies_response import AnnotationStudiesResponse


class TestAnnotationStudiesResponse(unittest.TestCase):
    """AnnotationStudiesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationStudiesResponse(self):
        """Test AnnotationStudiesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationStudiesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
