"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.series import Series
from igtcloud.client.services.entities.model.we_trust_series_all_of import WeTrustSeriesAllOf
from igtcloud.client.services.entities.model.we_trust_study import WeTrustStudy
globals()['Series'] = Series
globals()['WeTrustSeriesAllOf'] = WeTrustSeriesAllOf
globals()['WeTrustStudy'] = WeTrustStudy
from igtcloud.client.services.entities.model.we_trust_series import WeTrustSeries


class TestWeTrustSeries(unittest.TestCase):
    """WeTrustSeries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWeTrustSeries(self):
        """Test WeTrustSeries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WeTrustSeries()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
