"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.inline_object2 import InlineObject2


class TestInlineObject2(unittest.TestCase):
    """InlineObject2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject2(self):
        """Test InlineObject2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineObject2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
