"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.ai_suite_collection_all_of import AISuiteCollectionAllOf


class TestAISuiteCollectionAllOf(unittest.TestCase):
    """AISuiteCollectionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAISuiteCollectionAllOf(self):
        """Test AISuiteCollectionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AISuiteCollectionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
