"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.base_study_model import BaseStudyModel
from igtcloud.client.services.entities.model.echo_nav_model_all_of import EchoNavModelAllOf
from igtcloud.client.services.entities.model.patient_model import PatientModel
globals()['BaseStudyModel'] = BaseStudyModel
globals()['EchoNavModelAllOf'] = EchoNavModelAllOf
globals()['PatientModel'] = PatientModel
from igtcloud.client.services.entities.model.echo_nav_model import EchoNavModel


class TestEchoNavModel(unittest.TestCase):
    """EchoNavModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEchoNavModel(self):
        """Test EchoNavModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EchoNavModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
