"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.epd_site import EpdSite


class TestEpdSite(unittest.TestCase):
    """EpdSite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEpdSite(self):
        """Test EpdSite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EpdSite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
