"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.echo_nav import EchoNav
from igtcloud.client.services.entities.model.echo_nav_series_all_of import EchoNavSeriesAllOf
from igtcloud.client.services.entities.model.series import Series
globals()['EchoNav'] = EchoNav
globals()['EchoNavSeriesAllOf'] = EchoNavSeriesAllOf
globals()['Series'] = Series
from igtcloud.client.services.entities.model.echo_nav_series import EchoNavSeries


class TestEchoNavSeries(unittest.TestCase):
    """EchoNavSeries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEchoNavSeries(self):
        """Test EchoNavSeries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EchoNavSeries()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
