"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.epd_study_event_model import EpdStudyEventModel
globals()['EpdStudyEventModel'] = EpdStudyEventModel
from igtcloud.client.services.entities.model.epd_study_model_all_of import EpdStudyModelAllOf


class TestEpdStudyModelAllOf(unittest.TestCase):
    """EpdStudyModelAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEpdStudyModelAllOf(self):
        """Test EpdStudyModelAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EpdStudyModelAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
