"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.contact_model import ContactModel
from igtcloud.client.services.entities.model.organization_role_model import OrganizationRoleModel
globals()['ContactModel'] = ContactModel
globals()['OrganizationRoleModel'] = OrganizationRoleModel
from igtcloud.client.services.entities.model.profile_model import ProfileModel


class TestProfileModel(unittest.TestCase):
    """ProfileModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProfileModel(self):
        """Test ProfileModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProfileModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
