"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.storage_credentials import StorageCredentials


class TestStorageCredentials(unittest.TestCase):
    """StorageCredentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageCredentials(self):
        """Test StorageCredentials"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageCredentials()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
