"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.i_guide_u_study_model import IGuideUStudyModel
globals()['IGuideUStudyModel'] = IGuideUStudyModel
from igtcloud.client.services.entities.model.i_guide_u_studies_response import IGuideUStudiesResponse


class TestIGuideUStudiesResponse(unittest.TestCase):
    """IGuideUStudiesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIGuideUStudiesResponse(self):
        """Test IGuideUStudiesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IGuideUStudiesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
