"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.echo_nav_model import EchoNavModel
globals()['EchoNavModel'] = EchoNavModel
from igtcloud.client.services.entities.model.echo_nav_series_model_all_of import EchoNavSeriesModelAllOf


class TestEchoNavSeriesModelAllOf(unittest.TestCase):
    """EchoNavSeriesModelAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEchoNavSeriesModelAllOf(self):
        """Test EchoNavSeriesModelAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EchoNavSeriesModelAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
