"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.echo_nav_model_all_of import EchoNavModelAllOf


class TestEchoNavModelAllOf(unittest.TestCase):
    """EchoNavModelAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEchoNavModelAllOf(self):
        """Test EchoNavModelAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EchoNavModelAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
