"""
    Apis

    Api containing all apis  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.auth
from igtcloud.client.services.auth.model.s3_credential import S3Credential
globals()['S3Credential'] = S3Credential
from igtcloud.client.services.auth.model.s3_credential_response import S3CredentialResponse


class TestS3CredentialResponse(unittest.TestCase):
    """S3CredentialResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testS3CredentialResponse(self):
        """Test S3CredentialResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = S3CredentialResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
