"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.electronic_record_state import ElectronicRecordState


class TestElectronicRecordState(unittest.TestCase):
    """ElectronicRecordState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testElectronicRecordState(self):
        """Test ElectronicRecordState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ElectronicRecordState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
