"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.we_trust_study_model import WeTrustStudyModel
globals()['WeTrustStudyModel'] = WeTrustStudyModel
from igtcloud.client.services.entities.model.we_trust_studies_response import WeTrustStudiesResponse


class TestWeTrustStudiesResponse(unittest.TestCase):
    """WeTrustStudiesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWeTrustStudiesResponse(self):
        """Test WeTrustStudiesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WeTrustStudiesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
