"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.clinical_image_library_study_all_of import ClinicalImageLibraryStudyAllOf


class TestClinicalImageLibraryStudyAllOf(unittest.TestCase):
    """ClinicalImageLibraryStudyAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClinicalImageLibraryStudyAllOf(self):
        """Test ClinicalImageLibraryStudyAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClinicalImageLibraryStudyAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
