"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.user_activation_create_model import UserActivationCreateModel


class TestUserActivationCreateModel(unittest.TestCase):
    """UserActivationCreateModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserActivationCreateModel(self):
        """Test UserActivationCreateModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserActivationCreateModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
