"""
    Apis

    IGT Cloud entities  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import igtcloud.client.services.entities
from igtcloud.client.services.entities.model.core_labs_series_model import CoreLabsSeriesModel
globals()['CoreLabsSeriesModel'] = CoreLabsSeriesModel
from igtcloud.client.services.entities.model.core_labs_series_response import CoreLabsSeriesResponse


class TestCoreLabsSeriesResponse(unittest.TestCase):
    """CoreLabsSeriesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoreLabsSeriesResponse(self):
        """Test CoreLabsSeriesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CoreLabsSeriesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
